### ISSUE TITLE
Deprecated supported features

### ISSUE THREAD

**Issue by gab-fortunato** [MatteoManzoni/helty-cmv-integration-ha#1]
HA 2024.6.3
Helty CMV Integration integration 024b0e4 
I have some warnings in log:
Entity None (<class 'custom_components.heltycmv.fan.HeltyCMV'>) is using deprecated supported features values which will be removed in HA Core 2025.1.

At the moment all is well working.
Did you get some support from Helty HQ in Vicenza?

**Comment by MatteoManzoni** [comment]
Hey @gab-fortunato, I didn't get any support from Helty to develop the integration. 
I did ask for their approval for a possible release upstream (and the usage of their logos) tho, unfortunately I didn't have the time yet to focus on it.

As for the deprecation notice, I'm aware, I'll fix it before the release of 2025.1.

**Comment by MatteoManzoni** [comment]
https://github.com/MatteoManzoni/helty-cmv-integration-ha/commit/e134b7bd4569ed428e4f7faa265b69f4245ff616
Here's the fix to the deprecation
